baseURL  =  "https://chen.lms.im"
languageCode = "zh-CN"
# DefaultContentLanguage = "zh-CN"
title  =  "晨"
subtitle = "不问明天，悠然浪费"

theme  =  "blist"
summaryLength = 140
hasCJKLanguage = true
# 每页显示的文章数量用于分页
paginate =  10
# rss 输出数量
rssLimit = 5

[permalinks]
  posts = "/:filename/"
  tags = "/tags/:slug/"

[menu]
  [[menu.main]]
  name="归档"
  url="/archives/"
  weight="1"
  [[menu.main]]
  name="关于"
  url="/about/"
  weight="2"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  # showMenuItems = 4
  # Enable to show reading time in minutes for posts
  showReadingTime = false
  logoText = "hello friend"

  MenuMore = "更多"
  DateFormatList = "2006-01-02 15:04:05"
  DateFormatSingle = "2006-01-02 15:04:05"
  ReadMore = "阅读全文"

  EditPath = 'https://github.com/happyet/hugo-site/edit/master/content'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["Atom", "HTML","JSON"] # <domain>/atom.xml
  page = ["HTML"]
  
[outputFormats.Atom]
  mediatype = "application/rss"
  baseName = "atom"

[params.valine]
	enable = false
    appId = 'm6rxiyixBDG25mYPEPapQpnR-MdYXbMMI'
    appKey = 'WMokwNAwh9noJ4XeUjVBjsCt'
    placeholder = '既然来了，那就留个痕迹吧~'
    visitor = true
    serverURLs = "https://m6rxiyix.api.lncldglobal.com"

[params.twikoo]
	enable = true
